eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: ssi-ds
  datasource:
    druid:
      url: jdbc:oracle:thin:@192.168.1.1:1521:test
      username: user
      password: password
      driver-class-name: oracle.jdbc.driver.OracleDriver
      initial-size: 2
      max-active: 30
      min-idle: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ssi.dal.mapper
